version: '3.9'
services:

  frontend:
      container_name: products_frontend
      build: ./frontend
      ports:
        - 3000:3000
      platform: linux/x86_64
      working_dir: /app-frontend
      volumes:
        - ./frontend:/app-frontend
      depends_on:
        - backend

  backend:
    container_name: products_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ApiProducts

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./:/var/micro-data/mongodb/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=ApiProducts

